### ISSUE TITLE
JSON not serializable when running `makei init`

### ISSUE THREAD

**Issue by KerimG** [IBM/ibmi-bob#169]
Getting the following issue on `Bob version 2.4.0` when trying to initialize a project.

```
Traceback (most recent call last):
  File "/QOpenSys/pkgs/bin/makei", line 262, in <module>
    cli()
  File "/QOpenSys/pkgs/bin/makei", line 51, in cli
    args.handle(args)
  File "/QOpenSys/pkgs/bin/makei", line 191, in handle_init
    init_project.init_project(force=args.force)
  File "/QOpenSys/pkgs/lib/bob/makei/init_project.py", line 186, in init_project
    iproj_json_content = proj_spec.generate_iproj_json()
  File "/QOpenSys/pkgs/lib/bob/makei/init_project.py", line 96, in generate_iproj_json
    return json.dumps(iprojJson.__dict__, indent=4)
  File "/QOpenSys/pkgs/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/QOpenSys/pkgs/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/QOpenSys/pkgs/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/QOpenSys/pkgs/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'method' is not JSON serializable
```

**Comment by edmundreinhardt** [comment]
Problem reproduced in latest build
```
-bash-5.1$ mkdir newproj
-bash-5.1$ makei init
This utility will walk you through creating a project.
It only covers some common items.

Press ^C at any time to quit.
descriptive application name: (REINHARD) JSON serializable test
git repository: github.com/dummy
include path, separated by commas:
What library should objects be compiled into (objlib): (*CURLIB) MYLIB
What EBCDIC CCSID should the source be compiled in: (*JOB)
curlib: (*CRTDFT)
Pre user libraries, separated by commas:
Post user libraries, separated by commas:
Set up commands to be executed, separated by commas:
license: MIT
Traceback (most recent call last):
  File "/QOpenSys/pkgs/bin/makei", line 262, in <module>
    cli()
  File "/QOpenSys/pkgs/bin/makei", line 51, in cli
    args.handle(args)
  File "/QOpenSys/pkgs/bin/makei", line 191, in handle_init
    init_project.init_project(force=args.force)
  File "/QOpenSys/pkgs/lib/bob/makei/init_project.py", line 186, in init_project
    iproj_json_content = proj_spec.generate_iproj_json()
  File "/QOpenSys/pkgs/lib/bob/makei/init_project.py", line 96, in generate_iproj_json
    return json.dumps(iprojJson.__dict__, indent=4)
  File "/QOpenSys/pkgs/lib/python3.6/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/QOpenSys/pkgs/lib/python3.6/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/QOpenSys/pkgs/lib/python3.6/json/encoder.py", line 437, in _iterencode
    o = _default(o)
  File "/QOpenSys/pkgs/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'method' is not JSON serializable
-bash-5.1$```
