### ISSUE TITLE
mktemp is not fully qualified and is not found if PATH does not contain /QOpenSys/pkgs/bin

### ISSUE THREAD

**Issue by JDubbTX** [IBM/ibmi-bob#175]
I am getting a python type error when running builds in our corporate dev environment.  At the end of the build there is nothing in joblog.json, and the bottom of output.log has the bellow errors. 

Environment:  local windows development with vscode, deploying to ifs and building with Bob.
Bob version:  2.4.4

```
5770SS1 V7R4M0  190621                                              RDGJWEIRIC/UPD_SRV1    ITIDEV    11/27/22  15:18:12 UTC-06:00S
 Binding                          Binding                          Binding                          Binding
 Directory   Library              Directory   Library              Directory   Library              Directory   Library
 *NONE
 Total CPU time . . . . . . . . . . . . . . . . . . . . . . . :                .001
 Total elapsed time . . . . . . . . . . . . . . . . . . . . . :                .005
                                 * * * * *   E N D  O F  B I N D I N G  S T A T I S T I C S   * * * * *
*CPF5D05 - Service program UPD_SRV1 not created.
                    * * * * *   E N D  O F  C R E A T E  S E R V I C E  P R O G R A M  L I S T I N G   * * * * *
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/bob/scripts/getJobLog", line 38, in <module>
    cli()
  File "/QOpenSys/pkgs/lib/bob/scripts/getJobLog", line 34, in cli
    save_joblog_json(args.cmd, args.cmdtime, args.jobid, args.f)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 98, in save_joblog_json
    records = get_joblog_for_job(jobid)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 93, in get_joblog_for_job
    joblog_dict = query_job._dump_results_to_dict(results)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 63, in _dump_results_to_dict
    records, column_names = results
TypeError: 'NoneType' object is not iterable
/QOpenSys/pkgs/lib/bob/scripts/launch: line 21: mktemp: command not found
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CPC2198: Current library changed to RDGJWEIRIC.
ACMSLIB/ACMSLIBL REL(NELNET/GNF/GNFCORE) ENV(DVP) DVPNAME(JWEIRIC9)
CPD000D: Command ACMSLIB/ACMSLIBL not safe for a multithreaded job.
/QOpenSys/pkgs/lib/bob/scripts/launch: line 42: : No such file or directory
/QOpenSys/pkgs/lib/bob/scripts/launch: line 43: : No such file or directory
>> executing command: DLTOBJ OBJ(RDGJWEIRIC/BNDSTM2) OBJTYPE(*BNDDIR)
sed: The label :a;N;$!ba;s/\n/ /g is greater than eight characters.
>> liblist: 
>> executing time: 2022-11-27-15.18.17.%N

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/bob/scripts/getJobLog", line 38, in <module>
    cli()
  File "/QOpenSys/pkgs/lib/bob/scripts/getJobLog", line 34, in cli
    save_joblog_json(args.cmd, args.cmdtime, args.jobid, args.f)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 98, in save_joblog_json
    records = get_joblog_for_job(jobid)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 93, in get_joblog_for_job
    joblog_dict = query_job._dump_results_to_dict(results)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 63, in _dump_results_to_dict
    records, column_names = results
TypeError: 'NoneType' object is not iterable
/QOpenSys/pkgs/lib/bob/scripts/launch: line 21: mktemp: command not found
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CPC2198: Current library changed to RDGJWEIRIC.
ACMSLIB/ACMSLIBL REL(NELNET/GNF/GNFCORE) ENV(DVP) DVPNAME(JWEIRIC9)
CPD000D: Command ACMSLIB/ACMSLIBL not safe for a multithreaded job.
/QOpenSys/pkgs/lib/bob/scripts/launch: line 42: : No such file or directory
/QOpenSys/pkgs/lib/bob/scripts/launch: line 43: : No such file or directory
>> executing command: CRTBNDDIR BNDDIR(RDGJWEIRIC/BNDSTM2)
sed: The label :a;N;$!ba;s/\n/ /g is greater than eight characters.
>> liblist: 
>> executing time: 2022-11-27-15.18.19.%N

CPD000D: Command *LIBL/CRTBNDDIR not safe for a multithreaded job.
CPC5D02: Binding directory BNDSTM2 created in library RDGJWEIRIC.
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/bob/scripts/getJobLog", line 38, in <module>
    cli()
  File "/QOpenSys/pkgs/lib/bob/scripts/getJobLog", line 34, in cli
    save_joblog_json(args.cmd, args.cmdtime, args.jobid, args.f)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 98, in save_joblog_json
    records = get_joblog_for_job(jobid)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 93, in get_joblog_for_job
    joblog_dict = query_job._dump_results_to_dict(results)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 63, in _dump_results_to_dict
    records, column_names = results
TypeError: 'NoneType' object is not iterable
/QOpenSys/pkgs/lib/bob/scripts/launch: line 21: mktemp: command not found
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
CPC2198: Current library changed to RDGJWEIRIC.
ACMSLIB/ACMSLIBL REL(NELNET/GNF/GNFCORE) ENV(DVP) DVPNAME(JWEIRIC9)
CPD000D: Command ACMSLIB/ACMSLIBL not safe for a multithreaded job.
/QOpenSys/pkgs/lib/bob/scripts/launch: line 42: : No such file or directory
/QOpenSys/pkgs/lib/bob/scripts/launch: line 43: : No such file or directory
>> executing command:  ADDBNDDIRE BNDDIR(RDGJWEIRIC/BNDSTM2)  OBJ((*LIBL/SLA6UPR *SRVPGM) (*LIBL/SLA1UPR *SRVPGM) (*LIBL/SLA3UPR *SRVPGM)  (*LIBL/SLA4UPR *SRVPGM) (*LIBL/SLA5UPR *SRVPGM) (*LIBL/SLB2SRV *SRVPGM)  (*LIBL/SLA7UPR *SRVPGM) (*LIBL/SLA8UPR *SRVPGM) (*LIBL/SLJ1UPR *SRVPGM)  (*LIBL/SLA9UPR *SRVPGM) (*LIBL/UPD_SRV1 *SRVPGM) (*LIBL/SLJ2UPR *SRVPGM)  (*LIBL/SLJ4UPR *SRVPGM) (*LIBL/SLJ5UPR *SRVPGM) (*LIBL/SLA2UPR *SRVPGM) (*LIBL/SLJ8UPR *SRVPGM) (*LIBL/SLJ9UPR *SRVPGM) (*LIBL/SLP2UPR *SRVPGM))
sed: The label :a;N;$!ba;s/\n/ /g is greater than eight characters.
>> liblist: 
>> executing time: 2022-11-27-15.18.22.%N

CPD000D: Command *LIBL/ADDBNDDIRE not safe for a multithreaded job.
CPC5D05: 18 entries added, 0 entries not added to Binding directory BNDSTM2 in library RDGJWEIRIC.
<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/bob/scripts/getJobLog", line 38, in <module>
    cli()
  File "/QOpenSys/pkgs/lib/bob/scripts/getJobLog", line 34, in cli
    save_joblog_json(args.cmd, args.cmdtime, args.jobid, args.f)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 98, in save_joblog_json
    records = get_joblog_for_job(jobid)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 93, in get_joblog_for_job
    joblog_dict = query_job._dump_results_to_dict(results)
  File "/QOpenSys/pkgs/lib/bob/makei/ibm_job.py", line 63, in _dump_results_to_dict
    records, column_names = results
TypeError: 'NoneType' object is not iterable``

```

**Comment by JDubbTX** [comment]
Note that this happens when I invoke Bob from VSCODE, developing locally.  When I ran 'makei build' in an ssh session, I did not get this error, and the joblog was created.

**Comment by JDubbTX** [comment]
contents of my .profile:
![image](https://user-images.githubusercontent.com/56802156/206526390-555f4955-57de-4764-81f1-7b32c0e15231.png)
Not sure if VSCODE is using this environmental variable or not.  Let me dig into the docs a bit.

**Comment by JDubbTX** [comment]
I'm thinking it must not be using my path - When I start a PASE shell from within VSCODE, it has no problem finding the command.
![image](https://user-images.githubusercontent.com/56802156/206542981-a58a4a1f-20e6-4b34-b033-86d0ec7505ac.png)

**Comment by worksofliam** [comment]
@JDubbTX Correct. When Actions are run, it is run in a non-interactive shell.

https://www.vanimpe.eu/2014/01/18/different-shell-types-interactive-non-interactive-login/

**Comment by JDubbTX** [comment]
Ok, then I'm not sure how to set a path in the non interactive shell command.

**Comment by worksofliam** [comment]
@JDubbTX if bash is your default shell, look into using a .bashrc to setup the path.

**Comment by edmundreinhardt** [comment]
I assume this is now resolved
