### ISSUE TITLE
private TEXT:=value no longer working

### ISSUE THREAD

**Issue by edmundreinhardt** [IBM/ibmi-bob#194]
When we parse the variables they are interpreted as file names

```
BASH.MODULE: bash.c
BASH.MODULE:
	private TGTRLS:=V7R4M0
SH.MODULE: bash.c
SH.MODULE: private TEXT:='new text'
```
gets you
```
-bash-5.1$ makei c -f bash.c
targets: BASH.MODULE
Traceback (most recent call last):
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 277, in <module>
    cli()
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 44, in cli
    args.handle(args)
  File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 220, in handle_compile
    build_env = BuildEnv(targets, args.make_options, get_override_vars(args))
  File "/QOpenSys/pkgs/lib/bob/src/makei/build.py", line 68, in __init__
    self._create_build_vars()
  File "/QOpenSys/pkgs/lib/bob/src/makei/build.py", line 88, in _create_build_vars
    rules_mk = RulesMk.from_file(rules_mk_path, map(Path, self.iproj_json.include_path))
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 159, in from_file
    rules_mk = RulesMk.from_str(rules_mk_str, rules_mk_path.parent, include_dirs)
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 231, in from_str
    return RulesMk(subdir, rules, containing_dir)
  File "/QOpenSys/pkgs/lib/bob/src/makei/rules_mk.py", line 137, in __init__
    tgt_group = FILE_TARGETGROUPS_MAPPING[decompose_filename(rule.source_file)[-2]]
  File "/QOpenSys/pkgs/lib/bob/src/makei/utils.py", line 245, in decompose_filename
    raise ValueError(f"Cannot decomposite filename: {filename} as {ext} is not a recognized file extension")
ValueError: Cannot decomposite filename: private as PRIVATE is not a recognized file extension
```
in spite of following the docs at 
https://ibm.github.io/ibmi-bob/#/prepare-the-project/rules.mk?id=overriding-compile-settings

**Comment by edmundreinhardt** [comment]
@ThePrez Thanks for discovering this

**Comment by edmundreinhardt** [comment]
BUT

`TARGET.RPGLE: TEXT = My 50 char description`

works fine

**Comment by edmundreinhardt** [comment]
This is used in various files in http://github.com/IBM/bob-recursive-example like functionsVAT/Rules.mk

**Comment by edmundreinhardt** [comment]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/11184579/215633008-2c52f909-a484-463a-98af-b872e7012d4e.png">

Note that since it was not private, it applied to child target like the RPG MODULE was linked in.

Given this level of support, this issues is not as critical as it is only the support PRIVATE that is missing

**Comment by edmundreinhardt** [comment]
OK, the issue is that the Rules.mk parsing does not look for the := assignment.  Or rather it splits on the = leave `TEXT:` as the name of the variable.
