### ISSUE TITLE
Cannot compile source in a subdirectory

### ISSUE THREAD

**Issue by zkarj735** [IBM/ibmi-bob#209]
I have a directory with `iproj.json` at the root.
```
{
    "version": "0.0.1",
    "description": "Compile tools",
    "objlib": "&BUILDLIB",
    "curlib": "&BUILDLIB"
}
```
Then I have a subdirectory called `compile-tools` with various source files and a `Rules.mk`.
```
C_STDAUT.CMD: c_stdaut.cmdsrc
C_STDAUT.CMD: private PGM := C_STDAUT
C_STDAUT.CMD: private HLPPNLGRP := C_STDAUT
```
If I set the current directory to the parent and execute a compile with either of
`makei compile -f c_stdaut.cmdsrc -e BUILDLIB=AJENKS`
`makei compile -f compile-tools/c_stdaut.cmdsrc -e BUILDLIB=AJENKS`

I get errors:
```
Set variable <BUILDLIB> to 'AJENKS'
Traceback (most recent call last):
  File "/QOpenSys/pkgs/bin/makei", line 272, in <module>
    cli()
  File "/QOpenSys/pkgs/bin/makei", line 49, in cli
    args.handle(args)
  File "/QOpenSys/pkgs/bin/makei", line 207, in handle_compile
    build_env = BuildEnv(targets, args.make_options, get_override_vars(args))
  File "/QOpenSys/pkgs/lib/bob/makei/build.py", line 66, in __init__
    self._create_build_vars()
  File "/QOpenSys/pkgs/lib/bob/makei/build.py", line 101, in _create_build_vars
    list(map(map_ibmi_json_var, subdirs))
  File "/QOpenSys/pkgs/lib/bob/makei/build.py", line 99, in map_ibmi_json_var
    dir_var_map[path] = IBMiJson.from_file(path / ".ibmi.json", dir_var_map[path.parents[0]])
KeyError: PosixPath('builds')
```

If I change into the subdirectory, the compile (in the first form) works.

Furthermore, I tried to compile the entire subdirectory using `build` from the parent directory.
`makei build -d compile-tools -e BUILDLIB=AJENKS`
...and this failed...
```
Set variable <BUILDLIB> to 'AJENKS'
Traceback (most recent call last):
  File "/QOpenSys/pkgs/bin/makei", line 272, in <module>
    cli()
  File "/QOpenSys/pkgs/bin/makei", line 49, in cli
    args.handle(args)
  File "/QOpenSys/pkgs/bin/makei", line 224, in handle_build
    build_env = BuildEnv([target], args.make_options, get_override_vars(args))
  File "/QOpenSys/pkgs/lib/bob/makei/build.py", line 66, in __init__
    self._create_build_vars()
  File "/QOpenSys/pkgs/lib/bob/makei/build.py", line 101, in _create_build_vars
    list(map(map_ibmi_json_var, subdirs))
  File "/QOpenSys/pkgs/lib/bob/makei/build.py", line 99, in map_ibmi_json_var
    dir_var_map[path] = IBMiJson.from_file(path / ".ibmi.json", dir_var_map[path.parents[0]])
KeyError: PosixPath('builds')
```
Similarly, I tried the identical (according to documentation) `compile` variation.
`makei compile -f compile-tools -e BUILDLIB=AJENKS`
...and this fails, but in a different way.
```
Set variable <BUILDLIB> to 'AJENKS'
Traceback (most recent call last):
  File "/QOpenSys/pkgs/bin/makei", line 272, in <module>
    cli()
  File "/QOpenSys/pkgs/bin/makei", line 49, in cli
    args.handle(args)
  File "/QOpenSys/pkgs/bin/makei", line 206, in handle_compile
    targets = get_compile_targets_from_filenames(filenames)
  File "/QOpenSys/pkgs/lib/bob/makei/utils.py", line 228, in get_compile_targets_from_filenames
    result.append(get_target_from_filename(filename))
  File "/QOpenSys/pkgs/lib/bob/makei/utils.py", line 211, in get_target_from_filename
    name, _, ext, _ = decompose_filename(filename)
  File "/QOpenSys/pkgs/lib/bob/makei/utils.py", line 185, in decompose_filename
    raise ValueError(f"Cannot decomposite filename: {filename} as {ext} is not a recognized file extension")
ValueError: Cannot decomposite filename: compile-tools as COMPILE-TOOLS is not a recognized file extension
```

I'm trying to find a workable set of processes to develop small utilities without needing a git repository for each one (many of which will just be one or two source files). Splitting into subdirectories seems the logical way to go, but I am fighting at every turn.

bob has specific support for subdirectories, but it seems they don't work very well except in a full build (though I have not tested that!)

**Comment by beckhamrryyaann** [comment]
Do you also have a Rules.mk file in your top level directory.  This file should list all the sub directories that have source needing compiled.

**Comment by zkarj735** [comment]
Thanks, I created a root Rules.mk
```
SUBDIRS = compile-tools
```
However, both commands fail in the same ways still.

**Comment by zkarj735** [comment]
An update. I wondered whether a fresh deploy directory might make a difference. It does. There must have been something in the prior one that was upsetting things. I now have a working compile.
