### ISSUE TITLE
No module named 'ibm_db_dbi'

### ISSUE THREAD

**Issue by js-mason** [IBM/ibmi-bob#250]
Have followed the instructions for setting up the environment and insuring that prerequisites have been met. After installing bob, I am trying to verify the installation, and this is what I receive:

> make
    Traceback (most recent call last):
        File "/QOpenSys/pkgs/lib/bob/src/makei/cli/makei_entry.py", line 15, in <module>
           from makei.cvtsrcpf import CvtSrcPf
        File "/QOpenSys/pkgs/lib/bob/src/makei/cvtsrcpf.py", line 7, in <module>
           from makei.ibm_job import IBMJob
        File "/QOpenSys/pkgs/lib/bob/src/makei/ibm_job.py", line 10, in <module>
            import ibm_db_dbi
   ModuleNotFoundError: No module named 'ibm_db_dbi'
$

**Comment by edmundreinhardt** [comment]
investigating...

**Comment by js-mason** [comment]
Resolved issue by reinstalling Python libraries

**Comment by edmundreinhardt** [comment]
thank you!!!!
