### ISSUE TITLE
Failure in compilation when attempting to add library already in library list

### ISSUE THREAD

**Issue by AIforIBMi** [IBM/ibmi-bob#335]
Hello all!

I have observed a number of times when it comes to deploying projects which I am migrating to work with Project Explorer and Bob that listing a library in the .iproj.json file which already exists in my library list causes a compilation failure. I have provided a log below. Because of these projects, I am intentionally listing libraries which are dependencies of the project, but some have since been placed in the general user library list. I just wanted to point out this behavior. For now, I am simply listing the library list in the markdown, but I have been setting these up as a means for someone other than myself to easily pull a copy and make changes.

Thanks so much for all of the help!
```
CHGCURLIB CURLIB(devlib)
ADDLIBLE LIB(utils) POSITION(*FIRST)
[FAILED] ADDLIBLE LIB(utils) POSITION(*FIRST)
```
Traceback (most recent call last):
```
File "/QOpenSys/pkgs/lib/python3.9/site-packages/ibm_db_dbi.py", line 1193, in _callproc_helper
result = ibm_db.callproc(self.conn_handler, procname,parameters)
Exception: Statement Execute Failed: Trigger program or external routine detected an error. SQLSTATE=38501 SQLCODE=-443
```

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
```
File "/QOpenSys/pkgs/lib/bob/src/makei/crtfrmstmf.py", line 453, in
cli()
File "/QOpenSys/pkgs/lib/bob/src/makei/crtfrmstmf.py", line 342, in cli
success = handle.run()
File "/QOpenSys/pkgs/lib/bob/src/makei/crtfrmstmf.py", line 100, in run
self.setup_env()
File "/QOpenSys/pkgs/lib/bob/src/makei/crtfrmstmf.py", line 157, in setup_env
self.job.run_cl(f"ADDLIBLE LIB({libl}) POSITION(*FIRST)", log=True)
File "/QOpenSys/pkgs/lib/bob/src/makei/ibm_job.py", line 39, in run_cl
cursor.callproc("qsys2.qcmdexc", [cmd])
File "/QOpenSys/pkgs/lib/python3.9/site-packages/ibm_db_dbi.py", line 1220, in callproc
result = self._callproc_helper(procname, parameters)
File "/QOpenSys/pkgs/lib/python3.9/site-packages/ibm_db_dbi.py", line 1196, in _callproc_helper
raise self.messages[-1]
ibm_db_dbi.OperationalError: ibm_db_dbi::OperationalError: Exception('Statement Execute Failed: Trigger program or external routine detected an error. SQLSTATE=38501 SQLCODE=-443')
```

**Comment by AIforIBMi** [comment]
@bmcpherson-srlife
Thanks for opening this!

**Comment by edmundreinhardt** [comment]
@SanjulaGanepola thanks for the reference from https://github.com/IBM/vscode-ibmi-projectexplorer/issues/548

**Comment by edmundreinhardt** [comment]
@irfanshar I assume you didn't have a chance to address this?

**Comment by irfanshar** [comment]
> @irfanshar I assume you didn't have a chance to address this?

Not yet, will take a look this week
