### ISSUE TITLE
Inclusion of ✓ and ✕ in log

### ISSUE THREAD

**Issue by martintosney** [IBM/ibmi-bob#86]
First of all, I like the new changes in v2.3.5 to flag up where a build has failed. Very useful!

The tick symbol was causing problems for a user on our system who didn't have environment variables for his locale set. This led to errors like this:

```
=== Running SQL Statement from [REPLSRC.TABLE]
RUNSQLSTM srcstmf('/home/martint/code/rpgle-repl/db/REPLSRC.TABLE')
Traceback (most recent call last):
  File "/QOpenSys/pkgs/bin/makei", line 272, in <module>
    cli()
  File "/QOpenSys/pkgs/bin/makei", line 49, in cli
    args.handle(args)
  File "/QOpenSys/pkgs/bin/makei", line 225, in handle_build
    if build_env.make():
  File "/QOpenSys/pkgs/lib/bob/makei/build.py", line 137, in make
    run_command(self.generate_make_cmd(), handle_make_output)
  File "/QOpenSys/pkgs/lib/bob/makei/utils.py", line 211, in run_command
    stdoutHandler(line.decode('utf-8'))
  File "/QOpenSys/pkgs/lib/bob/makei/build.py", line 135, in handle_make_output
    print_to_stdout(line)
  File "/QOpenSys/pkgs/lib/bob/makei/utils.py", line 194, in print_to_stdout
    print(line, end="")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2713' in position 10: ordinal not in range(256)
make: *** [/QOpenSys/pkgs/lib/bob/mk/def_rules.mk:887: REPLVARS.SQL] Broken pipe
make: *** [/QOpenSys/pkgs/lib/bob/mk/def_rules.mk:887: REPLRSLT.SQL] Broken pipe
make: Target 'all' not remade because of errors.
```

I've set `LC_ALL` at a system level now, but I wonder if you could also restrict their output if the user's terminal doesn't support utf-8, similarly to how you condition whether colour codes are included.

Thanks!

**Comment by TongkunZhang** [comment]
Hi Martin, I will fix this in the next release.
Meanwhile, you may replace [line 16-25](https://github.com/IBM/ibmi-bob/blob/c54ea0d9627ef8da56f1242d0179ba792f3c467c/mk/def_rules.mk#L16) in `/QOpenSys/pkgs/lib/bob/mk/def_rules.mk` with
```makefile
ifeq ($(COLOR_TTY),true)
echo_prog := $(shell if echo -e | grep -q -- -e; then echo echo; else echo echo -e; fi)
echo_cmd = $(echo_prog) "$(COLOR)$(call strip_top,$(1))$(NOCOLOR)";
echo_success_cmd = ($(echo_prog) "$(SUCCESS_COLOR)$(call strip_top,$(1))$(NOCOLOR)" && echo)
echo_error_cmd = ($(echo_prog) "$(ERROR_COLOR)$(call strip_top,$(1))$(NOCOLOR)" && echo)
else
echo_cmd = @echo "$(call strip_top,$(1))";
echo_success_cmd = (echo "$(call strip_top,$(1))" && echo)
echo_error_cmd = (echo "$(call strip_top,$(1))" && echo)
endif
```
to temporarily resolve this issue on affected machines.
